stages:
  - build

variables:
  RAILS_ENV: "test"
  COVERAGE: "true"

build_code:
  stage: build
  script:
    - bundle install
    - mkdir -p test_output
    - cp config/database-gitlab.yml config/database.yml
    - bundle exec rake db:drop db:create db:migrate
    - bundle exec rubycritic -p "test_output/critic"
    - bundle exec rspec spec/
  tags:
    - ruby
#    - rails, ruby
  artifacts:
    paths:
      - test_output/