version: '3'
services:
   lazlo:
      build: .
      volumes:
         - ./:/usr/src/lazlo
         - ~/.ssh:/root/.ssh
      ports:
         - "3000:3000"
      depends_on:
         - lazlo_db
      stdin_open: true
      tty: true

   lazlo_db:
      image: mysql
      volumes:
         - ./db/lazlo_db_test:/var/lib/lazlo_db_test
      environment:
         MYSQL_ROOT_PASSWORD: sinclair

