version: '3'
services:
   lazlo:
      container_name: lazlo_ws
      stdin_open: true
      tty: true
      build: .
      volumes:
         - ./:/usr/src/lazlo
         - ~/.ssh:/root/.ssh
      ports:
         - "3000:3000"
      depends_on:
         - lazlo_db

   lazlo_db:
      container_name: lazlo_db
      image: mysql
      volumes:
         - ./db/lazlo_db_test:/var/lib/lazlo_db_test
      environment:
         MYSQL_ROOT_PASSWORD: sinclair

