version: '3'
services:
   alomacain:
      build: .
      volumes:
         - ./:/usr/src/alomacain
         - ~/.ssh:/root/.ssh
      ports:
         - "3000:3000"
      depends_on:
         - mysql
   mysql:
      image: mysql
      volumes:
         - ./db/mysql:/var/lib/mysql
      environment:
         MYSQL_ROOT_PASSWORD: sinclair
         MYSQL_PASSWORD: sinclair
         MYSQL_DATABASE: alomacain_test
         MYSQL_USER: test

