version: '3'
services:
   lazlo:
      container_name: lazlo_ws
      build: .
      stdin_open: ${DOCKERTTY}
      tty: ${DOCKERTTY}
      volumes:
         - ./:/usr/src/lazlo
         - ~/.ssh:/root/.ssh
         - ./public/system:/usr/src/lazlo/public/system
      ports:
         - 3000:3000
      depends_on:
         - db

   db:
      container_name: lazlo_db
      image: mysql
      volumes:
         - ./db/lazlo_db_test:/var/lib/lazlo_db_test
      environment:
         MYSQL_ROOT_PASSWORD: sinclair

