default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  host: lazlo_db_dev
  username: amalgama
  database: lazlo_dev
  password: sinclair

test:
  <<: *default
  host: lazlo_db_test
  username: amalgama
  database: lazlo_test
  password: sinclair
