default: &default
  adapter: mysql2
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  host: team_db_dev
  username: amalgama
  database: team_dev
  password: password

test:
  <<: *default
  host: team_db_test
  username: amalgama
  database: team_test
  password: password
