default: &default
  adapter: mysql2
  timeout: 5000
  encoding: utf8
  pool: <%= ENV.fetch('RAILS_MAX_THREADS') { 5 } %>
  username: test
  password: sinclair
  host: mysql

test:
  <<: *default
  database: lazlo_test
