default: &default
  endpoint: 'https://acme-v01.api.letsencrypt.org/'
  email: 'tomas@theamalgama.com'
  domain: macain.com.ar www.macain.com.ar

  # in Rails.root, path to private key
  private_key: '../../shared/key/keyfile.pem'

  # in Rails.root, path where certificates
  # will be stored (on Heroku this variable is ignored)
  output_cert_dir: '../../shared/certificates'

  # in Rails.root, path where challenge token
  # will be stored in case when DB will not be used
  challenge_dir_name: '../../shared/challenge'

production:
  cert_name: 'production'
  <<: *default

development:
  cert_name: 'development'
  <<: *default

test:
  cert_name: 'test'
  <<: *default

