development:
  secret_key_base: xxxxxxxxxx

  mercado_page_api_public_key: xxxxxxxxxx
  mercado_page_api_access_token: xxxxxxxxxx

  mercado_pago_client_id: xxxxxxxxxx
  mercado_pago_secret_id: xxxxxxxxxx

  instagram_access_token: xxxxxxxxxx
  instagram_client_id: xxxxxxxxxx
  instagram_client_secret: xxxxxxxxxx

staging:
  secret_key_base: xxxxxxxxxx

  mercado_page_api_public_key: xxxxxxxxxx
  mercado_page_api_access_token: xxxxxxxxxx

  mercado_pago_client_id: xxxxxxxxxx
  mercado_pago_secret_id: xxxxxxxxxx

  instagram_access_token: xxxxxxxxxx
  instagram_client_id: xxxxxxxxxx
  instagram_client_secret: xxxxxxxxxx

test:
  secret_key_base: xxxxxxxxxx

  mercado_page_api_public_key: xxxxxxxxxx
  mercado_page_api_access_token: xxxxxxxxxx

  mercado_pago_client_id: xxxxxxxxxx
  mercado_pago_secret_id: xxxxxxxxxx

  instagram_access_token: xxxxxxxxxx
  instagram_client_id: xxxxxxxxxx
  instagram_client_secret: xxxxxxxxxx

production:
  secret_key_base: xxxxxxxxxx

  mercado_page_api_public_key: xxxxxxxxxx
  mercado_page_api_access_token: xxxxxxxxxx

  mercado_pago_client_id: xxxxxxxxxx
  mercado_pago_secret_id: xxxxxxxxxx

  instagram_access_token: xxxxxxxxxx
  instagram_client_id: xxxxxxxxxx
  instagram_client_secret: xxxxxxxxxx